<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-K9GQO8KP" failures="1" tests="5" name="Error Validation" time="40.011" errors="0" timestamp="2023-07-18T14:58:41 IST">
  <testcase classname="learning.ErrorMessage" name="incorrectLogin" time="1.191"/>
  <testcase classname="learning.ErrorMessage" name="incorrectLogin" time="0.628"/>
  <testcase classname="learning.ErrorMessage" name="incorrectLogin" time="0.538"/>
  <testcase classname="learning.ErrorMessage" name="incorrectProductValidation" time="7.528">
    <skipped/>
  </testcase> <!-- incorrectProductValidation -->
  <testcase classname="learning.ErrorMessage" name="incorrectProductValidation" time="6.11">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at learning.ErrorMessage.incorrectProductValidation(ErrorMessage.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- incorrectProductValidation -->
</testsuite> <!-- Error Validation -->
